# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Common\Application\CommandBus $commandBus: '@Common\Infrastructure\Application\SymfonyMessengerCommandBus'
            Common\Application\QueryBus $queryBus: '@Common\Infrastructure\Application\SymfonyMessengerQueryBus'
            Blog\DomainModel\PostRepository $postRepository: '@Blog\Infrastructure\Persistence\Doctrine\Repository\DoctrinePostRepository'
            Blog\DomainModel\AuthorRepository $authorRepository: '@Blog\Infrastructure\Persistence\Doctrine\Repository\DoctrineAuthorRepository'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/App'
        exclude:
            - '../src/App/Entity/'
            - '../src/App/Kernel.php'

    App\Controller\:
        resource: '../src/App/Controller/'
        tags: [ 'controller.service_arguments' ]
#    App\Command\:
#        resource: '../src/App/Command'
#        tags: [ 'console.command' ]

    Blog\:
        resource: '../src/Blog'
        exclude:
            - '../src/Blog/Domain/'

    # Common
    Common\:
        resource: '../src/Common'
        exclude:
            - '../src/Common/Domain/'



    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    # Blog
    Blog\Application\Command\:
        resource: '../src/Blog/Application/Command'
        exclude:
            - '../src/Blog/Application/Command/**/*{Command.php,Query.php}'
        tags:
            - { name: messenger.message_handler, bus: command_bus }

    Blog\Application\Query\:
        resource: '../src/Blog/Application/Query/**/*QueryHandler.php'
        exclude:
            - '../src/Blog/Application/Query/**/*{Command.php,Query.php}'
        tags:
            - { name: messenger.message_handler, bus: query_bus }

    Blog\Infrastructure\:
        resource: '../src/Blog/Infrastructure'


